menu:
- {name: 'publications', url: '/publications'}
- {name: ' cv ', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'news', url: '/news'}

social:
- {icon: 'github', link: 'https://github.com/kateblomgren'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/katierinablomgren/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=dQbMpv8AAAAJ&hl=en'}

contact:
- { name: 'Caterina Blomgren', title: 'PhD Student', department: 'MIT', institution: 'Linköping University', email: 'caterina.blomgren@liu.se', office: 'Kopparhammaren 2, room 3053, Campus Norrköping\', image: 'assets/img/sticker-girl.png'
}
